name: First Workflow

on: push

jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
        - name: Welcome message
          run: echo 'My first actions'

        - name: List Files
          run: ls

        - name: Read file
          run: cat README.md


