name: Build Test and Deploy
on: push

jobs:
   build-job: 
    runs-on: ubuntu-latest
    steps:
        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsay CMD
          run: cowsay -f dragon "Run for cover, I feel a sneeze coming on." >> dragon.txt

        - name: Upload the artifact
          uses: actions/upload-artifact@v4
          with: 
            name: dragon-file
            path: dragon.txt 
    
   test-job:
    needs: build-job
    runs-on: ubuntu-latest
    steps:
        - name: Download the artifact
          uses: actions/download-artifact@v4
          with: 
            name: dragon-file

        - name: Test file Exist
          run: grep -i "dragon" dragon.txt

   deploy_job:
        needs: test-job
        runs-on: ubuntu-latest
        steps:
            - name: Download the artifact
              uses: actions/download-artifact@v4
              with: 
                name: dragon-file

            - name: Read file
              run: cat dragon.txt
            
            - name: List the files
              run: ls -ltra
  



